In [1]:
import pandas as pd
import numpy as np

In [4]:
sample_df = pd.DataFrame({'col1': range(0,100),
                                    'col2': range(1,200,2)})
sample_df

    col1  col2
0      0     1
1      1     3
2      2     5
3      3     7
4      4     9
..   ...   ...
95    95   191
96    96   193
97    97   195
98    98   197
99    99   199

[100 rows x 2 columns]

In [ ]:
sample_df.head() #Mostras as 5 primeiras linhas do DataFrame. Caso queira ver as 3 primeiras linhas -> sapmle.df.head(3)

   col1  col2
0     0     1
1     1     3
2     2     5
3     3     7
4     4     9

In [ ]:
sample_df.tail()#Mostra as 5 últimas linhas do DataFrame. Caso queira ver as 3 últimas linhas -> sapmle.df.tail(3)

Primeiro, observe que DataFrame é uma classe da biblioteca pandas, portanto, pode ser instanciada chamando pd.DataFrame() (assumindo que pandas seja importado como pd, que é a convenção comumente usada).

Você pode verificar o tipo de dados da variável sample_df usando o código a seguir, chamando a função type() do núcleo do Python, da seguinte forma: 

type(sample_df_construction)

Isso resultará na seguinte saída:

pandas.core.frame.DataFrame

Você pode ver que, além de fornecer dados, é possível especificar o índice e as colunas e forçar um tipo de dados específico (dtype). Na descrição do parâmetro data, observe que data pode ser um array NumPy, um iterável, um dicionário (dict) ou um DataFrame.

Para cada coluna, existe um par chave:valor, onde a chave se torna o nome da coluna e o valor se torna o dado na coluna. Como um dicionário pode lidar com qualquer tipo de dado, essa forma permite que estruturas complexas sejam adicionadas a uma coluna.

O próximo exemplo mostra a diferença entre usar um dicionário (como no exemplo anterior) e usar outros tipos de dados. No trecho de código a seguir, você primeiro carrega a biblioteca NumPy e cria alguns arrays usando np.array(). 

Observe que np.array() é uma função que cria um array NumPy, e um array é uma estrutura com uma ou mais dimensões para armazenar dados numéricos. Aqui, você está criando duas matrizes unidimensionais: